# Parte individual prueba 1 machine learning

In [38]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("C:\\Users\\musrr\\Downloads\\Variables.csv", delimiter=';')

Luego de importar pandas y matplotlib.pyplot para poder realizar graficos, agregamos el documento .csv, en el cual modificamos la base de datos puesto que esta separada por ';', y a continuacion mapeamos el sexo de 1 de mujer y 2 de hombre para que tengan sus valores dados por el diccionarios, y hacemos lo mismo con tamaño, categoria y grupo, para luego aplicar los cambios y mostrar los primeros 5 datos con un .head para así ver si se realizaron los cambios

In [46]:
#Definir los numeros y letras a sus respectivas categorias
mapeo_sexo = {1: 'Mujer', 2: 'Hombre'}
mapeo_tamano = {1: 'Pequeño', 2: 'Mediana', 3: 'Grande'}
mapeo_categoria = {
    'B': 'Minería',
    'C': 'Industria Manufacturera',
    'D': 'Suministro de Electricidad, Gas, Vapor y Aire Acondicionado',
    'E': 'Suministro de Agua, Evacuación de Aguas Residuales, Gestión de Desechos y Descontaminación',
    'F': 'Construcción',
    'G': 'Comercio',
    'H': 'Transporte y Almacenamiento',
    'I': 'Actividades de Alojamiento y Servicio de Comidas',
    'J': 'Información y Comunicaciones',
    'K': 'Actividades Financieras y de Seguros',
    'L': 'Actividades Inmobiliarias',
    'M': 'Actividades Profesionales, Científicas y Técnicas',
    'N': 'Actividades de Servicios Administrativos y de Apoyo',
    'O': 'Administración Pública',
    'P': 'Enseñanza',
    'Q': 'Actividades de Atención de la Salud Humana y de Asistencia Social',
    'R': 'Actividades Artísticas, de Entretenimiento y Recreativas'}
mapeo_grupo = {
    1: 'Directores y gerentes',
    2: 'Profesionales',
    3: 'Técnicos',
    4: 'Trabajadores de apoyo administrativo',
    5: 'Trabajadores de servicios personales, protección y seguridad',
    6: 'Vendedores, promotores y modelos',
    7: 'Operarios manuales y artesanos',
    8: 'Operadores y montadores de instalaciones y máquinas',
    9: 'Trabajadores no especializados'}

# Aplicar los cambios a sus respectivas categorias
df['sexo'] = df['sexo'].replace(mapeo_sexo)
df['tamano'] = df['tamano'].replace(mapeo_tamano)
df['categoria'] = df['categoria'].replace(mapeo_categoria)
df['grupo'] = df['grupo'].replace(mapeo_grupo)
# Mostrar el df con un .head()
df.head()

,ano,mes,id,tamano,categoria,sexo,grupo,div,ro_t_1,ho_t_1,c_t_1,ht_t_1,ro,ho,c,ht
0,2023,7,984,Mediana,Comercio,Mujer,Directores y gerentes,1,8146341,195.00,8351617.00,195.00,9032064,203.00,9256676.00,203.00
1,2023,7,984,Mediana,Comercio,Mujer,Profesionales,1,119995721,4492.00,122707290.00,4517.00,102745916,4209.00,105330382.00,4209.00
2,2023,7,984,Mediana,Comercio,Mujer,Técnicos,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023,7,984,Mediana,Comercio,Mujer,Trabajadores de apoyo administrativo,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023,7,984,Mediana,Comercio,Mujer,"Trabajadores de servicios personales, protecci...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

A continuacion se convierte los valores no numericos de la columna 'ro_t_1' y si posee alguna clase de error se transforman a valor NaN

In [32]:
df['ro_t_1'] = pd.to_numeric(df['ro_t_1'], errors='coerce')

A continuacion se eliminan los valores nulos del target

In [34]:
df = df.dropna(subset=['ro_t_1'])

Para no tener problemas de interpretacion transforme los valores elevados a numeros con 2 decimales, luego agrupo por sexo el target y presento los valores estadisticos de la misma.

In [ ]:
pd.set_option('display.float_format', '{:.2f}'.format)

Aquí muestro las medidas de tendencia central con respecto a la columna 'ro_t_1' la cual es la remuneracion y la vemos con los valores de las categorias, los separo por sexo y su respectivo grupo, por desgracia son tantos valores que llega a ser practicamente imposible mostrarlos todos en un mismo grupo, por lo mismo en los siguientes codigos los separamos de distintas agrupaciones.

In [51]:
resultados = df.groupby(['categoria', 'sexo', 'grupo']).agg({
    'ro_t_1': ['mean', 'median', 'std', 'min', 'max']
}).reset_index()
resultados.head(300)

                                             categoria    sexo  \

0    Actividades Artísticas, de Entretenimiento y R...  Hombre
1    Actividades Artísticas, de Entretenimiento y R...  Hombre
2    Actividades Artísticas, de Entretenimiento y R...  Hombre
3    Actividades Artísticas, de Entretenimiento y R...  Hombre
4    Actividades Artísticas, de Entretenimiento y R...  Hombre
..                                                 ...     ...
295                        Transporte y Almacenamiento   Mujer
296                        Transporte y Almacenamiento   Mujer
297                        Transporte y Almacenamiento   Mujer
298                        Transporte y Almacenamiento   Mujer
299                        Transporte y Almacenamiento   Mujer

                                                 grupo       ro_t_1  \
                                                               mean
0                                Directores y gerentes  19646353.31
1    Operadores y montadores de instalaciones y máq...   5778528.88
2                       Operarios manuales y artesanos   7000992.65
3                                        Profesionales  37599726.80
4                 Trabajadores de apoyo administrativo  16415831.07
..                                                 ...          ...
295               Trabajadores de apoyo administrativo  45808481.54
296  Trabajadores de servicios personales, protecci... 124919305.94
297                     Trabajadores no especializados  21154072.55
298                                           Técnicos  46501647.02
299                   Vendedores, promotores y modelos  13347535.10


         median          std       min          max
0   10258930.00  32605935.79 470232.00 213795952.00
1    2163180.00  10550822.58 121262.00  46237351.00
2    4090982.50   7724645.59 145768.00  34444433.00
3   11038474.00  94752017.76 360634.00 693166504.00
4    4136543.00  29698068.22 222291.00 150051265.00
..          ...          ...       ...          ...
295 14450023.00  99044663.44 550000.00 611333858.00
296  3453081.00 278890257.71 599562.00 829671110.00
297  4338897.50  54291441.76  38320.00 343027379.00
298 12555982.50 129150742.96  22536.00 956830431.00
299  4075087.50  15649632.53 572292.00  42415240.00

[300 rows x 8 columns]

In [52]:
grupos_por_sexo = df.groupby('sexo')['ro_t_1']

estadisticos_sexo = grupos_por_sexo.describe()

estadisticos_sexo.head()

,count,mean,std,min,25%,50%,75%,max
sexo,,,,,,,,
Hombre,8884.00,142857824.58,448796882.30,13869.00,5800758.75,24672245.00,94127928.75,10053364551.00
Mujer,7617.00,105887741.25,398052037.29,14200.00,3368985.00,13684236.00,54014303.00,8352488403.00

Agrupamos el target ahora con los grupos y calculamos sus estadisticas descriptivas de manera individual

In [53]:
grupos_por_grupo = df.groupby('grupo')['ro_t_1']
estadisticos_grupo = grupos_por_grupo.describe()

estadisticos_grupo.head(9)

,count,mean,std,min,25%,50%,75%,max
grupo,,,,,,,,
Directores y gerentes,2428.00,73737263.75,205145582.63,178719.00,7878528.75,21877986.50,63947436.25,5220897350.00
Operadores y montadores de instalaciones y máquinas,1171.00,116302711.61,362172723.41,23335.00,2190893.00,11353570.00,56426234.50,4145082961.00
Operarios manuales y artesanos,1142.00,135060399.83,458879615.73,14200.00,2871880.25,15198716.50,76395168.75,6929493221.00
Profesionales,2963.00,307421820.34,793079526.60,45833.00,10223455.00,49187412.00,238392244.00,10053364551.00
Trabajadores de apoyo administrativo,2925.00,59611184.10,170286882.04,56269.00,3606392.00,14583088.00,47457644.00,3052763077.00
"Trabajadores de servicios personales, protección y seguridad",733.00,62031209.18,209608183.51,134880.00,1594770.00,6496676.00,31484330.00,3108092093.00
Trabajadores no especializados,1893.00,66494060.27,213015613.62,18345.00,2012000.00,9161304.00,42643518.00,4059795172.00
Técnicos,2765.00,108742507.73,320115202.93,13869.00,5912920.00,23027167.00,81699636.00,6995663730.00
"Vendedores, promotores y modelos",481.00,101795378.27,243832539.40,15206.00,3238384.00,17438511.00,77585843.00,2471626622.00

Agrupo el target ahora con las categorias y calculamos sus estadisticas descriptivas de manera individual

In [54]:
grupos_por_categoria = df.groupby('categoria')['ro_t_1']
estadisticos_categoria = grupos_por_categoria.describe()
estadisticos_categoria.head(17)

,count,mean,std,min,25%,50%,75%,max
categoria,,,,,,,,
"Actividades Artísticas, de Entretenimiento y Recreativas",809.00,18714052.03,56747100.82,18345.00,1771948.00,6132527.00,15967581.00,1011850374.00
Actividades Financieras y de Seguros,792.00,272391954.95,883098091.67,35134.00,7560525.50,41108388.50,181897873.00,10053364551.00
Actividades Inmobiliarias,386.00,26015558.70,61919096.25,21793.00,1609726.75,5288425.00,19285610.00,493854604.00
"Actividades Profesionales, Científicas y Técnicas",749.00,74879545.96,202574585.50,24445.00,2437774.00,9976201.00,45435491.00,2297269274.00
Actividades de Alojamiento y Servicio de Comidas,789.00,78732654.96,272695934.68,14200.00,3260475.00,12152242.00,38257261.00,4059795172.00
Actividades de Atención de la Salud Humana y de Asistencia Social,905.00,164208094.64,450890515.38,69414.00,5106253.00,23684197.00,108178499.00,4500426560.00
Actividades de Servicios Administrativos y de Apoyo,1291.00,92231343.62,280954619.31,106546.00,4315742.00,17686551.00,69070493.50,5184734096.00
Administración Pública,1671.00,201042536.99,615336641.68,63996.00,15047370.50,45050092.00,122028619.00,7671504347.00
Comercio,1704.00,125953655.82,318844210.32,15206.00,4802992.75,23011440.00,101988458.50,3909720500.00
Construcción,1882.00,69250248.09,260919347.97,13869.00,2938058.75,10890378.00,43136834.25,6198698832.00
Enseñanza,881.00,220246307.12,653445527.91,69384.00,8459021.00,37468176.00,130611401.00,9991954901.00
Industria Manufacturera,2347.00,89180357.34,253266778.49,72284.00,6153233.00,20320034.00,66229185.50,6027452285.00
Información y Comunicaciones,405.00,176935671.78,493735022.47,55000.00,3981221.00,14719244.00,94598294.00,4450245921.00
Minería,486.00,296647847.39,714479297.62,124655.00,3280819.50,25784371.00,183405791.50,6929493221.00
"Suministro de Agua, Evacuación de Aguas Residuales, Gestión de Desechos y Descontaminación",374.00,60506031.84,148177603.06,220002.00,3333500.75,12196748.50,44751824.50,1559022402.00
"Suministro de Electricidad, Gas, Vapor y Aire Acondicionado",180.00,172589760.54,360104031.59,706424.00,8124120.00,36633160.50,148038434.75,2486893079.00
Transporte y Almacenamiento,850.00,111919196.47,321865053.27,22536.00,3717302.00,18101080.50,78145145.50,4312079189.00

Agrupo el grupo con el sexo para diferenciar los grupos con sus respectivos sexos.

In [11]:
grupos_por_grupo_y_sexo = df.groupby(['grupo', 'sexo'])['ro_t_1']
estadisticos_grupo_sexo = grupos_por_grupo_y_sexo.describe()
estadisticos_grupo_sexo.head(20)

                                                            count  \
grupo                                              sexo
Directores y gerentes                              Hombre 1383.00
                                                   Mujer  1045.00
Operadores y montadores de instalaciones y máqu... Hombre  808.00
                                                   Mujer   363.00
Operarios manuales y artesanos                     Hombre  711.00
                                                   Mujer   431.00
Profesionales                                      Hombre 1511.00
                                                   Mujer  1452.00
Trabajadores de apoyo administrativo               Hombre 1418.00
                                                   Mujer  1507.00
Trabajadores de servicios personales, protecció... Hombre  421.00
                                                   Mujer   312.00
Trabajadores no especializados                     Hombre  968.00
                                                   Mujer   925.00
Técnicos                                           Hombre 1423.00
                                                   Mujer  1342.00
Vendedores, promotores y modelos                   Hombre  241.00
                                                   Mujer   240.00

                                                                  mean  \
grupo                                              sexo
Directores y gerentes                              Hombre  95738801.30
                                                   Mujer   44619439.43
Operadores y montadores de instalaciones y máqu... Hombre 156781262.70
                                                   Mujer   26201694.30
Operarios manuales y artesanos                     Hombre 180711802.36
                                                   Mujer   59751473.60
Profesionales                                      Hombre 337864946.99
                                                   Mujer  275741679.60
Trabajadores de apoyo administrativo               Hombre  49674581.99
                                                   Mujer   68960953.05
Trabajadores de servicios personales, protecció... Hombre  67386182.05
                                                   Mujer   54805428.48
Trabajadores no especializados                     Hombre  76852589.89
                                                   Mujer   55653999.00
Técnicos                                           Hombre 121523302.27
                                                   Mujer   95190294.14
Vendedores, promotores y modelos                   Hombre 103459579.61
                                                   Mujer  100124242.75

                                                                   std  \
grupo                                              sexo
Directores y gerentes                              Hombre 249007021.84
                                                   Mujer  119441188.46
Operadores y montadores de instalaciones y máqu... Hombre 425433062.58
                                                   Mujer   93066498.39
Operarios manuales y artesanos                     Hombre 543088798.53
                                                   Mujer  250225617.86
Profesionales                                      Hombre 822475679.54
                                                   Mujer  760274298.77
Trabajadores de apoyo administrativo               Hombre 130685296.64
                                                   Mujer  200127545.50
Trabajadores de servicios personales, protecció... Hombre 225348368.23
                                                   Mujer  186386325.20
Trabajadores no especializados                     Hombre 196545151.69
                                                   Mujer  228591979.16
Técnicos                                           Hombre 321574947.78
                                                   Mujer  318119064.30
Vendedores, promotores y modelos                   Hombre 249877649.70
                                                   Mujer  238118568.81

                                                                min  \
grupo                                              sexo
Directores y gerentes                              Hombre 178719.00
                                                   Mujer  202748.00
Operadores y montadores de instalaciones y máqu... Hombre  36666.00
                                                   Mujer   23335.00
Operarios manuales y artesanos                     Hombre  35957.00
                                                   Mujer   14200.00
Profesionales                                      Hombre  45833.00
                                                   Mujer   59669.00
Trabajadores de apoyo administrativo               Hombre  56269.00
                                                   Mujer   79875.00
Trabajadores de servicios personales, protecció... Hombre 176884.00
                                                   Mujer  134880.00
Trabajadores no especializados                     Hombre  51354.00
                                                   Mujer   18345.00
Técnicos                                           Hombre  13869.00
                                                   Mujer   22536.00
Vendedores, promotores y modelos                   Hombre  21793.00
                                                   Mujer   15206.00

                                                                  25%  \
grupo                                              sexo
Directores y gerentes                              Hombre  9976888.50
                                                   Mujer   6458334.00
Operadores y montadores de instalaciones y máqu... Hombre  4173184.25
                                                   Mujer    877719.50
Operarios manuales y artesanos                     Hombre  5289620.00
                                                   Mujer   1778165.00
Profesionales                                      Hombre 14573748.00
                                                   Mujer   7844885.25
Trabajadores de apoyo administrativo               Hombre  3655139.25
                                                   Mujer   3462791.00
Trabajadores de servicios personales, protecció... Hombre  1731392.00
                                                   Mujer   1488965.00
Trabajadores no especializados                     Hombre  3065525.75
                                                   Mujer   1443220.00
Técnicos                                           Hombre  8056772.00
                                                   Mujer   4581129.25
Vendedores, promotores y modelos                   Hombre  3266334.00
                                                   Mujer   3108369.00

                                                                  50%  \
grupo                                              sexo
Directores y gerentes                              Hombre 30708128.00
                                                   Mujer  14759351.00
Operadores y montadores de instalaciones y máqu... Hombre 20942003.50
                                                   Mujer   2622076.00
Operarios manuales y artesanos                     Hombre 29368238.00
                                                   Mujer   6508619.00
Profesionales                                      Hombre 64833122.00
                                                   Mujer  35249796.50
Trabajadores de apoyo administrativo               Hombre 13761259.50
                                                   Mujer  15143116.00
Trabajadores de servicios personales, protecció... Hombre  8212632.00
                                                   Mujer   4650835.50
Trabajadores no especializados                     Hombre 14639353.50
                                                   Mujer   5540523.00
Técnicos                                           Hombre 30339278.00
                                                   Mujer  15977997.50
Vendedores, promotores y modelos                   Hombre 15404720.00
                                                   Mujer  18173457.00

                                                                   75%  \
grupo                                              sexo
Directores y gerentes                              Hombre  86501705.00
                                                   Mujer   37787924.00
Operadores y montadores de instalaciones y máqu... Hombre  85299497.25
                                                   Mujer   13357175.50
Operarios manuales y artesanos                     Hombre 137329353.50
                                                   Mujer   26861655.50
Profesionales                                      Hombre 278085036.50
                                                   Mujer  205058512.50
Trabajadores de apoyo administrativo               Hombre  44067831.25
                                                   Mujer   51360611.50
Trabajadores de servicios personales, protecció... Hombre  34767868.00
                                                   Mujer   25896501.75
Trabajadores no especializados                     Hombre  67021953.25
                                                   Mujer   23340079.00
Técnicos                                           Hombre 101969131.50
                                                   Mujer   59870279.25
Vendedores, promotores y modelos                   Hombre  87450373.00
                                                   Mujer   72722090.75

                                                                     max
grupo                                              sexo
Directores y gerentes                              Hombre  5220897350.00
                                                   Mujer   2282155610.00
Operadores y montadores de instalaciones y máqu... Hombre  4145082961.00
                                                   Mujer    996323241.00
Operarios manuales y artesanos                     Hombre  6929493221.00
                                                   Mujer   2659982851.00
Profesionales                                      Hombre 10053364551.00
                                                   Mujer   8352488403.00
Trabajadores de apoyo administrativo               Hombre  2050338594.00
                                                   Mujer   3052763077.00
Trabajadores de servicios personales, protecció... Hombre  3108092093.00
                                                   Mujer   2087077683.00
Trabajadores no especializados                     Hombre  2149838377.00
                                                   Mujer   4059795172.00
Técnicos                                           Hombre  5184734096.00
                                                   Mujer   6995663730.00
Vendedores, promotores y modelos                   Hombre  2471626622.00
                                                   Mujer   1997557119.00

Ahora agrupamos las categorias con los grupos y como son tantas categorias en los distintos grupos estas no se pueden ver en su totalidad

In [57]:
grupos_por_grupo_y_categoria = df.groupby(['grupo', 'categoria'])['ro_t_1']
estadisticos_grupo_categoria = grupos_por_grupo_y_categoria.describe()
estadisticos_grupo_categoria.head(151)

                                                                                     count  \
grupo                            categoria
Directores y gerentes            Actividades Artísticas, de Entretenimiento y Re...  99.00
                                 Actividades Financieras y de Seguros               173.00
                                 Actividades Inmobiliarias                           68.00
                                 Actividades Profesionales, Científicas y Técnicas  137.00
                                 Actividades de Alojamiento y Servicio de Comidas    95.00
...                                                                                    ...
Vendedores, promotores y modelos Industria Manufacturera                            106.00
                                 Información y Comunicaciones                        14.00
                                 Minería                                              1.00
                                 Suministro de Agua, Evacuación de Aguas Residua...   4.00
                                 Transporte y Almacenamiento                         17.00

                                                                                            mean  \
grupo                            categoria
Directores y gerentes            Actividades Artísticas, de Entretenimiento y Re...  16568511.46
                                 Actividades Financieras y de Seguros               201856638.07
                                 Actividades Inmobiliarias                           45501451.53
                                 Actividades Profesionales, Científicas y Técnicas   71848298.17
                                 Actividades de Alojamiento y Servicio de Comidas    28799821.09
...                                                                                          ...
Vendedores, promotores y modelos Industria Manufacturera                             83656722.15
                                 Información y Comunicaciones                        90186832.43
                                 Minería                                               531666.00
                                 Suministro de Agua, Evacuación de Aguas Residua...   2896322.25
                                 Transporte y Almacenamiento                         20076876.82

                                                                                             std  \
grupo                            categoria
Directores y gerentes            Actividades Artísticas, de Entretenimiento y Re...  27761354.68
                                 Actividades Financieras y de Seguros               550721005.15
                                 Actividades Inmobiliarias                           91621407.16
                                 Actividades Profesionales, Científicas y Técnicas  162467535.28
                                 Actividades de Alojamiento y Servicio de Comidas    46875846.14
...                                                                                          ...
Vendedores, promotores y modelos Industria Manufacturera                            199410780.32
                                 Información y Comunicaciones                       116304426.21
                                 Minería                                                     NaN
                                 Suministro de Agua, Evacuación de Aguas Residua...    630061.49
                                 Transporte y Almacenamiento                         31482735.63

                                                                                           min  \
grupo                            categoria
Directores y gerentes            Actividades Artísticas, de Entretenimiento y Re...  470232.00
                                 Actividades Financieras y de Seguros                304095.00
                                 Actividades Inmobiliarias                           249671.00
                                 Actividades Profesionales, Científicas y Técnicas   440000.00
                                 Actividades de Alojamiento y Servicio de Comidas    178719.00
...                                                                                        ...
Vendedores, promotores y modelos Industria Manufacturera                             323555.00
                                 Información y Comunicaciones                         55000.00
                                 Minería                                             531666.00
                                 Suministro de Agua, Evacuación de Aguas Residua... 1959056.00
                                 Transporte y Almacenamiento                         572292.00

                                                                                            25%  \
grupo                            categoria
Directores y gerentes            Actividades Artísticas, de Entretenimiento y Re...  4012447.50
                                 Actividades Financieras y de Seguros               17336636.00
                                 Actividades Inmobiliarias                           4784796.75
                                 Actividades Profesionales, Científicas y Técnicas   5298315.00
                                 Actividades de Alojamiento y Servicio de Comidas    4613671.00
...                                                                                         ...
Vendedores, promotores y modelos Industria Manufacturera                             3631005.75
                                 Información y Comunicaciones                        4765880.75
                                 Minería                                              531666.00
                                 Suministro de Agua, Evacuación de Aguas Residua...  2810499.50
                                 Transporte y Almacenamiento                         2221085.00

                                                                                            50%  \
grupo                            categoria
Directores y gerentes            Actividades Artísticas, de Entretenimiento y Re...  9171622.00
                                 Actividades Financieras y de Seguros               50734445.00
                                 Actividades Inmobiliarias                          11313217.00
                                 Actividades Profesionales, Científicas y Técnicas  14841709.00
                                 Actividades de Alojamiento y Servicio de Comidas   11872201.00
...                                                                                         ...
Vendedores, promotores y modelos Industria Manufacturera                            15008387.50
                                 Información y Comunicaciones                       12337572.50
                                 Minería                                              531666.00
                                 Suministro de Agua, Evacuación de Aguas Residua...  3179949.50
                                 Transporte y Almacenamiento                         6408350.00

                                                                                             75%  \
grupo                            categoria
Directores y gerentes            Actividades Artísticas, de Entretenimiento y Re...  14895074.50
                                 Actividades Financieras y de Seguros               158239451.00
                                 Actividades Inmobiliarias                           41240458.00
                                 Actividades Profesionales, Científicas y Técnicas   49758796.00
                                 Actividades de Alojamiento y Servicio de Comidas    33247862.00
...                                                                                          ...
Vendedores, promotores y modelos Industria Manufacturera                             59402200.00
                                 Información y Comunicaciones                       228292166.50
                                 Minería                                               531666.00
                                 Suministro de Agua, Evacuación de Aguas Residua...   3265772.25
                                 Transporte y Almacenamiento                         26698261.00

                                                                                              max
grupo                            categoria
Directores y gerentes            Actividades Artísticas, de Entretenimiento y Re...  213795952.00
                                 Actividades Financieras y de Seguros               5220897350.00
                                 Actividades Inmobiliarias                           493854604.00
                                 Actividades Profesionales, Científicas y Técnicas  1140509934.00
                                 Actividades de Alojamiento y Servicio de Comidas    323123850.00
...                                                                                           ...
Vendedores, promotores y modelos Industria Manufacturera                            1132438767.00
                                 Información y Comunicaciones                        265321384.00
                                 Minería                                                531666.00
                                 Suministro de Agua, Evacuación de Aguas Residua...    3266334.00
                                 Transporte y Almacenamiento                         130175369.00

[151 rows x 8 columns]

Y como ultima estadistica esta categoria con sexo

In [60]:
grupos_por_categoria_sexo = df.groupby(['categoria', 'sexo'])['ro_t_1']
estadisticos_categoria_sexo = grupos_por_categoria_sexo.describe()
estadisticos_categoria_sexo.head(300)

                                                            count  \
categoria                                          sexo
Actividades Artísticas, de Entretenimiento y Re... Hombre  441.00
                                                   Mujer   368.00
Actividades Financieras y de Seguros               Hombre  414.00
                                                   Mujer   378.00
Actividades Inmobiliarias                          Hombre  200.00
                                                   Mujer   186.00
Actividades Profesionales, Científicas y Técnicas  Hombre  394.00
                                                   Mujer   355.00
Actividades de Alojamiento y Servicio de Comidas   Hombre  409.00
                                                   Mujer   380.00
Actividades de Atención de la Salud Humana y de... Hombre  462.00
                                                   Mujer   443.00
Actividades de Servicios Administrativos y de A... Hombre  667.00
                                                   Mujer   624.00
Administración Pública                             Hombre  871.00
                                                   Mujer   800.00
Comercio                                           Hombre  917.00
                                                   Mujer   787.00
Construcción                                       Hombre 1082.00
                                                   Mujer   800.00
Enseñanza                                          Hombre  459.00
                                                   Mujer   422.00
Industria Manufacturera                            Hombre 1293.00
                                                   Mujer  1054.00
Información y Comunicaciones                       Hombre  211.00
                                                   Mujer   194.00
Minería                                            Hombre  277.00
                                                   Mujer   209.00
Suministro de Agua, Evacuación de Aguas Residua... Hombre  206.00
                                                   Mujer   168.00
Suministro de Electricidad, Gas, Vapor y Aire A... Hombre  101.00
                                                   Mujer    79.00
Transporte y Almacenamiento                        Hombre  480.00
                                                   Mujer   370.00

                                                                  mean  \
categoria                                          sexo
Actividades Artísticas, de Entretenimiento y Re... Hombre  22765140.68
                                                   Mujer   13859350.68
Actividades Financieras y de Seguros               Hombre 275777433.73
                                                   Mujer  268684049.62
Actividades Inmobiliarias                          Hombre  33629281.59
                                                   Mujer   17828759.89
Actividades Profesionales, Científicas y Técnicas  Hombre 102071788.60
                                                   Mujer   44699986.52
Actividades de Alojamiento y Servicio de Comidas   Hombre  66194187.78
                                                   Mujer   92228005.16
Actividades de Atención de la Salud Humana y de... Hombre 117621228.09
                                                   Mujer  212793043.51
Actividades de Servicios Administrativos y de A... Hombre 114555466.78
                                                   Mujer   68368859.41
Administración Pública                             Hombre 168519401.48
                                                   Mujer  236452100.78
Comercio                                           Hombre 135111226.29
                                                   Mujer  115283399.00
Construcción                                       Hombre 107899816.52
                                                   Mujer   16976706.78
Enseñanza                                          Hombre 188524726.22
                                                   Mujer  254749164.07
Industria Manufacturera                            Hombre 130759209.61
                                                   Mujer   38173283.36
Información y Comunicaciones                       Hombre 247847043.03
                                                   Mujer   99810417.49
Minería                                            Hombre 444639678.17
                                                   Mujer  100505564.49
Suministro de Agua, Evacuación de Aguas Residua... Hombre  91818001.55
                                                   Mujer   22111592.78
Suministro de Electricidad, Gas, Vapor y Aire A... Hombre 257997423.44
                                                   Mujer   63397685.19
Transporte y Almacenamiento                        Hombre 159812279.96
                                                   Mujer   49787628.69

                                                                   std  \
categoria                                          sexo
Actividades Artísticas, de Entretenimiento y Re... Hombre  57455549.84
                                                   Mujer   55575671.36
Actividades Financieras y de Seguros               Hombre 947764465.49
                                                   Mujer  807591220.36
Actividades Inmobiliarias                          Hombre  76376263.87
                                                   Mujer   39673438.12
Actividades Profesionales, Científicas y Técnicas  Hombre 259148870.71
                                                   Mujer  102061510.73
Actividades de Alojamiento y Servicio de Comidas   Hombre 182352695.04
                                                   Mujer  344184906.43
Actividades de Atención de la Salud Humana y de... Hombre 379999968.80
                                                   Mujer  510452854.48
Actividades de Servicios Administrativos y de A... Hombre 349761430.15
                                                   Mujer  177666561.26
Administración Pública                             Hombre 488443816.56
                                                   Mujer  727469903.77
Comercio                                           Hombre 320895607.20
                                                   Mujer  316306364.88
Construcción                                       Hombre 336935576.42
                                                   Mujer   43801938.73
Enseñanza                                          Hombre 667439219.33
                                                   Mujer  636872346.68
Industria Manufacturera                            Hombre 323096463.04
                                                   Mujer  100477596.22
Información y Comunicaciones                       Hombre 638686230.72
                                                   Mujer  234428159.68
Minería                                            Hombre 894656555.37
                                                   Mujer  245757490.67
Suministro de Agua, Evacuación de Aguas Residua... Hombre 188819988.01
                                                   Mujer   50821113.34
Suministro de Electricidad, Gas, Vapor y Aire A... Hombre 451509422.71
                                                   Mujer  121269061.74
Transporte y Almacenamiento                        Hombre 401492975.40
                                                   Mujer  149175249.95

                                                                 min  \
categoria                                          sexo
Actividades Artísticas, de Entretenimiento y Re... Hombre   71162.00
                                                   Mujer    18345.00
Actividades Financieras y de Seguros               Hombre   35134.00
                                                   Mujer    82391.00
Actividades Inmobiliarias                          Hombre   21793.00
                                                   Mujer   162115.00
Actividades Profesionales, Científicas y Técnicas  Hombre   45833.00
                                                   Mujer    24445.00
Actividades de Alojamiento y Servicio de Comidas   Hombre  139212.00
                                                   Mujer    14200.00
Actividades de Atención de la Salud Humana y de... Hombre   69414.00
                                                   Mujer   134880.00
Actividades de Servicios Administrativos y de A... Hombre  131501.00
                                                   Mujer   106546.00
Administración Pública                             Hombre  445528.00
                                                   Mujer    63996.00
Comercio                                           Hombre   35957.00
                                                   Mujer    15206.00
Construcción                                       Hombre   13869.00
                                                   Mujer    50681.00
Enseñanza                                          Hombre  200313.00
                                                   Mujer    69384.00
Industria Manufacturera                            Hombre  119075.00
                                                   Mujer    72284.00
Información y Comunicaciones                       Hombre   55000.00
                                                   Mujer   171210.00
Minería                                            Hombre  124655.00
                                                   Mujer   147910.00
Suministro de Agua, Evacuación de Aguas Residua... Hombre  220002.00
                                                   Mujer   349032.00
Suministro de Electricidad, Gas, Vapor y Aire A... Hombre  706424.00
                                                   Mujer  1025201.00
Transporte y Almacenamiento                        Hombre  235713.00
                                                   Mujer    22536.00

                                                                  25%  \
categoria                                          sexo
Actividades Artísticas, de Entretenimiento y Re... Hombre  2042531.00
                                                   Mujer   1582363.25
Actividades Financieras y de Seguros               Hombre  7870404.75
                                                   Mujer   7192462.25
Actividades Inmobiliarias                          Hombre  1933940.25
                                                   Mujer   1389676.75
Actividades Profesionales, Científicas y Técnicas  Hombre  2728657.75
                                                   Mujer   2267877.00
Actividades de Alojamiento y Servicio de Comidas   Hombre  3281109.00
                                                   Mujer   3065924.00
Actividades de Atención de la Salud Humana y de... Hombre  5016483.50
                                                   Mujer   5570912.50
Actividades de Servicios Administrativos y de A... Hombre  6210115.50
                                                   Mujer   3499574.75
Administración Pública                             Hombre 16313595.50
                                                   Mujer  13790601.00
Comercio                                           Hombre  5508563.00
                                                   Mujer   3785101.50
Construcción                                       Hombre  5512357.25
                                                   Mujer   1870372.00
Enseñanza                                          Hombre  6701441.00
                                                   Mujer  10576521.25
Industria Manufacturera                            Hombre 10108585.00
                                                   Mujer   3959316.00
Información y Comunicaciones                       Hombre  4767014.00
                                                   Mujer   3432955.00
Minería                                            Hombre  4051496.00
                                                   Mujer   2462951.00
Suministro de Agua, Evacuación de Aguas Residua... Hombre  5465745.75
                                                   Mujer   2180260.00
Suministro de Electricidad, Gas, Vapor y Aire A... Hombre 13266078.00
                                                   Mujer   6370487.00
Transporte y Almacenamiento                        Hombre  5481902.50
                                                   Mujer   2355015.50

                                                                  50%  \
categoria                                          sexo
Actividades Artísticas, de Entretenimiento y Re... Hombre  7439650.00
                                                   Mujer   4865023.50
Actividades Financieras y de Seguros               Hombre 44941998.50
                                                   Mujer  36124139.50
Actividades Inmobiliarias                          Hombre  6275357.50
                                                   Mujer   4417774.50
Actividades Profesionales, Científicas y Técnicas  Hombre 12447316.50
                                                   Mujer   8419701.00
Actividades de Alojamiento y Servicio de Comidas   Hombre 13214736.00
                                                   Mujer  11820190.50
Actividades de Atención de la Salud Humana y de... Hombre 17013103.50
                                                   Mujer  38819425.00
Actividades de Servicios Administrativos y de A... Hombre 23085708.00
                                                   Mujer  13100158.50
Administración Pública                             Hombre 45083459.00
                                                   Mujer  44873984.00
Comercio                                           Hombre 27513047.00
                                                   Mujer  18436521.00
Construcción                                       Hombre 23118257.00
                                                   Mujer   5409370.00
Enseñanza                                          Hombre 29485173.00
                                                   Mujer  48310104.00
Industria Manufacturera                            Hombre 32525676.00
                                                   Mujer  12114694.00
Información y Comunicaciones                       Hombre 22186001.00
                                                   Mujer  12406487.00
Minería                                            Hombre 48090005.00
                                                   Mujer  15381904.00
Suministro de Agua, Evacuación de Aguas Residua... Hombre 26171921.50
                                                   Mujer   6323170.50
Suministro de Electricidad, Gas, Vapor y Aire A... Hombre 74961821.00
                                                   Mujer  19930761.00
Transporte y Almacenamiento                        Hombre 31748458.00
                                                   Mujer   9468757.00

                                                                   75%  \
categoria                                          sexo
Actividades Artísticas, de Entretenimiento y Re... Hombre  18662023.00
                                                   Mujer   12932998.50
Actividades Financieras y de Seguros               Hombre 171797590.00
                                                   Mujer  186240976.00
Actividades Inmobiliarias                          Hombre  28610489.25
                                                   Mujer   16685152.00
Actividades Profesionales, Científicas y Técnicas  Hombre  61196501.75
                                                   Mujer   31324032.50
Actividades de Alojamiento y Servicio de Comidas   Hombre  40487503.00
                                                   Mujer   34745963.75
Actividades de Atención de la Salud Humana y de... Hombre  67349025.75
                                                   Mujer  160069498.50
Actividades de Servicios Administrativos y de A... Hombre  90046266.00
                                                   Mujer   48831276.75
Administración Pública                             Hombre 106062556.00
                                                   Mujer  141945849.75
Comercio                                           Hombre 121649105.00
                                                   Mujer   72363548.00
Construcción                                       Hombre  80873222.25
                                                   Mujer   15149543.75
Enseñanza                                          Hombre  95854826.00
                                                   Mujer  186986800.75
Industria Manufacturera                            Hombre 109145302.00
                                                   Mujer   32890428.00
Información y Comunicaciones                       Hombre 145886986.50
                                                   Mujer   59348733.50
Minería                                            Hombre 423716195.00
                                                   Mujer   74989469.00
Suministro de Agua, Evacuación de Aguas Residua... Hombre  84787042.50
                                                   Mujer   17348556.75
Suministro de Electricidad, Gas, Vapor y Aire A... Hombre 281168269.00
                                                   Mujer   52247131.00
Transporte y Almacenamiento                        Hombre 134602848.75
                                                   Mujer   33764420.50

                                                                     max
categoria                                          sexo
Actividades Artísticas, de Entretenimiento y Re... Hombre   693166504.00
                                                   Mujer   1011850374.00
Actividades Financieras y de Seguros               Hombre 10053364551.00
                                                   Mujer   8352488403.00
Actividades Inmobiliarias                          Hombre   493854604.00
                                                   Mujer    301304275.00
Actividades Profesionales, Científicas y Técnicas  Hombre  2297269274.00
                                                   Mujer    828727310.00
Actividades de Alojamiento y Servicio de Comidas   Hombre  1585469932.00
                                                   Mujer   4059795172.00
Actividades de Atención de la Salud Humana y de... Hombre  4500426560.00
                                                   Mujer   4102891417.00
Actividades de Servicios Administrativos y de A... Hombre  5184734096.00
                                                   Mujer   2076341426.00
Administración Pública                             Hombre  5233210098.00
                                                   Mujer   7671504347.00
Comercio                                           Hombre  3909720500.00
                                                   Mujer   3173966750.00
Construcción                                       Hombre  6198698832.00
                                                   Mujer    888265341.00
Enseñanza                                          Hombre  9991954901.00
                                                   Mujer   7046367728.00
Industria Manufacturera                            Hombre  6027452285.00
                                                   Mujer   1550257492.00
Información y Comunicaciones                       Hombre  4450245921.00
                                                   Mujer   1567236436.00
Minería                                            Hombre  6929493221.00
                                                   Mujer   2380429296.00
Suministro de Agua, Evacuación de Aguas Residua... Hombre  1559022402.00
                                                   Mujer    388821641.00
Suministro de Electricidad, Gas, Vapor y Aire A... Hombre  2486893079.00
                                                   Mujer    710134722.00

Como conclusión podemos notar que muchos mas hombres posee remuneración en comparación a las mujeres, puesto que hay casí 9000 hombres y menos casí 7600 mujeres, lo cual nos muestra que en gran parte hay muchos mas hombres con trabajo que mujeres, por otra parte se puede ver que la remuneración minima en hombres es menor a la de las mujeres, pero la remuneracion maxima en los hombres es bastante mayor, con casí 2 millones de diferencia.